### ISSUE TITLE
Asset filtering

### ISSUE THREAD

**Issue by myurasov** [electricimp/Builder#11]
- Escape characters to be included in strings
- Base64 encode binary data
- Custom/tbd

Possible syntax:

```
@include <filtername> <source>
```

```
@{<expression>|<filtername>}
```

```
@{include(<source>)|<filtername>}
```

```
@{include(<source>, <filtername>)}
```

**Comment by rlipscombe** [comment]
I prefer `@{<expression>|<filtername>}`, because it feels more like (e.g.) Django, and it gives you scope to provide arguments to the filter in future, syntactically.

**Comment by myurasov** [comment]
e1f603b9c8e79ccb25ddbcd15c5130b86c4066e1
- added "filter" operator `|`
- added `escape`, `base64` filters
- functions, macros can also be used as filters (eg `value | macro` is equivalent to `macro(value)`
