### ISSUE TITLE
Strings do not support all characters

### ISSUE THREAD

**Issue by blake-regalia** [electricimp/Builder#13]
Strings do not support arbitrary characters.
Suppose you want to pass a tiny bit of code to your macro:

``` js
@macro set(val)
    let someVar = @{val};
@end

@{set('{}')}
```

The `'{'` character in the string causes the error:

``` sh
Unclosed quote after "{" at character 6 (builder-bug.js:5)
```

There's no way to escape the character either.
However, here is an inconvenient work-around:

``` js
@set str '{}'

@macro set(val)
    let someVar = @{val};
@end

@{set(str)}
```

**Comment by ppetrosh** [comment]
The problem as far as I can see it is at the line:
AstParser.js:210 which can't parse `@{set('{}')}` as it terminates at the first closing '}' and resolves `@{set('{`, which breaks the parser. 

Making it less hungry `@{(.?)}` doesn't work either as it would erroneously parse expressions like: `@{set('{A}')} @{set('{B}')}` (resolving the entire expression between {...}: `set('{A}')} @{set('{B}')`). So I believe either a proper escaping should be used for curly brackets or the regexp should be improved.
