### ISSUE TITLE
Allow trailing comments for all builder directives

### ISSUE THREAD

**Issue by deldrid1** [electricimp/Builder#28]
Similar to the behavior for *@include*: https://github.com/electricimp/Builder/blob/abecf203f12b566e8cb04e4689c5d7fe99953964/spec/Machine/include-comments.spec.js#L17-L24

all builder directives should allow for end of line contents.  For example, I would expect the following to work:
```
@if METER_PROTOCOL_REV == 2.02  // We support 2 different version of the meter protocol
  @set PERIODIC_DATA_PERIOD = 200  //milliseconds
@else // Use the legacy mode
  @set METER_PROTOCOL_REV 1.07  
  @set PERIODIC_DATA_PERIOD = 1 //seconds
@end
```

However, it produces the following error:  `Error: Expected expression after / at character 29 (Meter.singleton.nut:12)`

**Comment by deldrid1** [comment]
It may be as simple as moving 

https://github.com/electricimp/Builder/blob/develop/src/AstParser.js#L117-L118

up above the switch on L114?

**Comment by ppetrosh** [comment]
https://github.com/electricimp/Builder/pull/29

**Comment by deldrid1** [comment]
Fixed!
