### ISSUE TITLE
Allow @function directive to include node.js Builder Function definitions

### ISSUE THREAD

**Issue by deldrid1** [electricimp/Builder#30]
I’d like to add a code fence to each of our included files with a macro so that the (quite large) final compiled file can be easily collapsed into its various includes.  It might look like something along these lines:
 ```
// =============================================================================
// METER  ----------------------------------------------------------------------
// ============================================================================{
License information and other header related things go here
 
Class implementation…
.
.
.
 ```
 
```
// =============================================================================
// ------------------------------------------------------------------- END_METER
// ============================================================================}
 ```
 

The Builder Macro would look something like this
```
@macro HEADER(file)
@set file STR_toUpper(STR_split(file, “.”, 0)
// =============================================================================
// @{file} @{STR_repeat(“-“, 77 - length(file)}
// ============================================================================{
License information and other header related things go here
 
@endmacro
 ```

```
@macro FOOTER(file)
@set file STR_toUpper(STR_split(file, “.”, 0)
// =============================================================================
// @{STR_repeat(“-“, 72 - length(file)} END_@{file}
// ============================================================================}
License information and other header related things go here
@endmacro
 ```
 
 
To use the macro, this would be included in my source files:
 
```
@{HEADER(__FILE__)}            //__FILE__ is Meter.singleton.nut
Class implementation…
.
.
.
@{FOOTER(__FILE__)}
```

In order to be able to do this, Builder needs to support some basic string manipulation functions.  For this particular use case, implementing the following would be sufficient:
- STR_toUpper
- STR_split
- STR_repeat

However, to be even more flexible long term, I think that Builder should allow `@function` directives or a directory of node.js files in a specific format to define these kind of functions using JavaScript.  With this kind of capability, defining a library of functions (or even exposing whole JS libraries for really advanced capabilities) should be pretty straightforward.  Re-implementing all the function defined in https://github.com/electricimp/Builder/blob/b146f88fe338d88448c9315cc1ecc0d1be64e0ce/src/index.js#L50 should be pretty low effort too I think?

@ppetrosh - thoughts?

**Comment by ppetrosh** [comment]
It makes sense to me. I like the idea of having a middleware that would allow you to define the Builder language extensions functionality.

**Comment by jayeheffernan** [comment]
@deldrid1 @ppetrosh I hadn't seen this but I wanted the feature myself so I could define my own filters for `@include`s.  I've mocked up a working solution along the lines of "a directory of node.js files in a specific format to define these kind of functions using JavaScript".  I'll try to submit a pull request in the next few days, and you can take a look at the syntax etc. to see if you're happy.

**Comment by jayeheffernan** [comment]
@deldrid1  @ppetrosh [the pull request](https://github.com/electricimp/Builder/pull/34) is up if you'd like to take a look.  It certainly covers the functionality proposed by @deldrid1  above and I've tried to keep restrictions on the format of the included files to a minimum.
