### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by deldrid1** [electricimp/Builder#41]
Can builder support the use of a proxy server (on windows)?  

request.js seems to support this use case out of the box: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

However, I’m not positive that github@0.2.4: (which has now been renamed to '@octokit/rest' https://git.io/vNB11) is respecting proxies correctly per https://github.com/octokit/rest.js/issues/770 and I think it might need to be updated?  Ideally, it would support respecting HTTP_PROXY and HTTPS_PROXY environment variables…
 
 Node.js’s decision to not go down the “slippery slope” of supporting proxy servers in the core (https://github.com/nodejs/node/issues/15620) makes things much more difficult then they need to be…  Unfortunately, I can confirm that Proxy support is not working currently...

**Comment by ppetrosh** [comment]
Working on this one now... should be ready by the end of the week or early next week.

**Comment by ppetrosh** [comment]
Fixed.
