### ISSUE TITLE
Return relative path to included file with error in the Builder error message

### ISSUE THREAD

**Issue by FedorUporov** [electricimp/Builder#49]
Consider the next project structure:

include.nut:
@include "notexist.file" // <= File does not exist

device.nut:
@include "./someRelativePath/include3.nut"

In this case we have next Builder error:
Error: Local file "notexist.file" not found (include.nut:1).

So, the problem is, that it is difficult to find absolute path to include.nut file from error message.
It would be great if error will looks like 'Error: Local file "notexist.file" not found (./someRelativePath/include.nut:1).' or if it will be possible to get this relative path by some other way.

**Comment by ppetrosh** [comment]
To be honest I don't fully understand why that's required? Can you please elaborate on the use-case?

It's not fully clear how to fix it, which "relative" path to display. I.e. what should it be relative to?

**Comment by ppetrosh** [comment]
It's not fully clear how to fix it, which "relative" path to display. I.e. what should it be relative to?

**Comment by FedorUporov** [comment]
Yep, current working directory or directory with device.nut in case above. I know the full path to device.nut. Then I can extract relative path from error ./someRelativePath/include.nut and concatenate it with path to directory, where the device.nut file is placed.
