### ISSUE TITLE
'@include once' can't handle same directories accessed relatively

### ISSUE THREAD

**Issue by CoderScribe** [electricimp/Builder#73]
Hi guys,

'@include once' is a great feature that has allowed us to start treating our source code in a highly modular manner as we would in traditional languages, by placing includes in the files where they're required, irrespective of their use elsewhere in the program.

We have found this usage limited, however, as the builder seems unable to distinguish inclusion of the same file when arrived upon via different routes i.e.:
@include once "compiler/lib/Serializer.class.nut";
@include once "Serializer.class.nut";

Both may be speaking of the same absolute directory, however the builder seems unable to determine this.

This becomes particularly limiting when including stand-alone libraries, as it forces us to use absolute naming within the library to avoid duplicates, but this falls apart when then including/building that library from within a larger project, which has led us to create build scripts that pre-build our libraries first.

Any chance for an enhancement in this area?

**Comment by alexey-nbl** [comment]
fixed already
