### ISSUE TITLE
Builder issues in Windows enviroment

### ISSUE THREAD

**Issue by GustafKisi** [electricimp/Builder#76]
I am trying to get my environment up and running. We use Builder to merge files into agent and device files, and then we use 'impt build deploy' command to deploy to a specific device group. I'm using Windows PowerShell in Windows 10.

First I run the Builder command:

`pleasebuild device.nut > device.built.nut`

Then I'm trying to run this command:

`impt build deploy --dg 54468d5c-9e7f-767b-7e4d-94e3c05d692a --device-file .\device.built.nut`

And I'm getting this error message: 

`Error: Invalid Character: The value may not contain embedded NUL (\u0000).
IMPT COMMAND FAILS`

My colleagues work on Macs and are not getting any of these error messages. 

If I run the deploy command on plain files it uploads without any issues, it's when I try to upload the files that Builder actually creates I get errors.

Any ideas?

**Comment by ce07c3** [comment]
The extension for VSCode doesn't work either I fear.

**Comment by betzrhodes** [comment]
Thanks for reporting the issue. I'll add it to our backlog. Unfortunately we currently do not have a timeline when we can share a fix. We will keep this issue open till we are able to reproduce it and find a possible fix/workaround. Apologies if this impedes your progress.

**Comment by ce07c3** [comment]
No worries. This also affects the VSCode extension I believe.

**Comment by GustafKisi** [comment]
@betzrhodes any updates?

**Comment by alexey-nbl** [comment]
@GustafKisi could you please provide an example source file which results to the issue.
We tried different builder directives and options but are not able to reproduce the issue.
The only similar issue we got when the original file really contains 0x00 byte.

**Comment by GustafKisi** [comment]
@alexey-nbl Hi, I solved this issue by running WSL, windows subsystem for Linux,  and running all commands from there.
