### ISSUE TITLE
Can't include GitHub files when using Builder in the VSCode extension

### ISSUE THREAD

**Issue by ragrus-nbl** [electricimp/Builder#99]
I get "Unknown error: (exit code 1)" when trying to include a GitHub file using Builder via [the VSCode extension](https://github.com/electricimp/vscode).
The `pleasebuild` command works fine in this case.

After some time of debugging, I figured out that the problem is [here](https://github.com/electricimp/Builder/blob/master/src/Readers/GithubReader.js#L74):
```
    const child = childProcess.spawnSync(
      /* node */ process.argv[0],   <<----- 
      ^^^ This is a reference not to node but to Electron when running Builder via VSCode
      [/* self */ __filename,
        WORKER_MARKER,
        source,
        this.username,
        this.token,
        gitBlobID,
      ],
      { timeout: this.timeout }
    );
```

OS: macOS Big Sur
VSCode: v1.64.0

**Comment by alexey-nbl** [comment]
A quick fix:
```
    // spawn child process
    const child = childProcess.spawnSync(
      // /* node */ process.argv[0],
      // In VSCode on maсOS, process.argv[0] is ".../Electron" - not ".../node"
      "node",
      [/* self */ __filename,
        WORKER_MARKER,
        source,
        this.username,
        this.token,
        gitBlobID,
      ],
      { timeout: this.timeout }
    );
```
But it's more like a crutch.
May not work in some cases.
Needs additional investigation.
Ideally - the Github reader should be refactored - but it's significant efforts.
